name: Smart Money Scanner
on:
  schedule:
    # 04:00 UTC is exactly 09:30 AM IST (The Early Wake Up Trick)
    - cron: '00 4 * * 1-5' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # Added a 20-minute safety limit
    timeout-minutes: 20 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python anomaly_scanner.py
